-- 1. Town Dimension
COPY dim_town (town_id, town_name) 
FROM '/tmp/real_estate_csvs/town.csv' 
DELIMITER ',' CSV HEADER;

-- 2. Property Type Dimension
COPY dim_property_type (property_type_id, type) 
FROM '/tmp/real_estate_csvs/property_type.csv' 
DELIMITER ',' CSV HEADER;

-- 3. Date Dimension
-- Note: Maps explicitly to the columns generated by our Python script
COPY dim_date (date_recorded_id, month, day, quarter, year, full_date) 
FROM '/tmp/real_estate_csvs/date.csv' 
DELIMITER ',' CSV HEADER;

-- 4. Address Dimension
COPY dim_address (address_id, address, town_id, longitude, latitude) 
FROM '/tmp/real_estate_csvs/address.csv' 
DELIMITER ',' CSV HEADER;



-- 5. Household Debt Fact
-- Maps to: low, high, date_recorded_id
COPY fact_household_debt (lower_bound, upper_bound, date_recorded_id) 
FROM '/tmp/real_estate_csvs/household_debt.csv' 
DELIMITER ',' CSV HEADER;

-- 6. Unemployment Rate Fact
-- Maps to: rate, date_recorded_id
COPY fact_unemployment_rate (rate, date_recorded_id) 
FROM '/tmp/real_estate_csvs/unemployment.csv' 
DELIMITER ',' CSV HEADER;

-- 7. Affordable Housing Fact
-- Maps to: census_units, total_assisted_units, rate, town_id, date_recorded_id
COPY fact_affordable_housing (census_units, total_assisted_units, rate, town_id, date_recorded_id) 
FROM '/tmp/real_estate_csvs/affordable_housing.csv' 
DELIMITER ',' CSV HEADER;

-- 8. Real Estate Transaction Fact (The 1.1 Million Row Table)
-- Maps to: ID, Serial Number, Assessed Value, Sale Amount, Sales Ratio, Address ID, Property Type ID, Date Recorded ID
COPY fact_real_estate_transaction (transaction_id, serial_number, assessed_value, sales_amount, sales_ratio, address_id, property_type_id, date_recorded_id) 
FROM '/tmp/real_estate_csvs/real_estate.csv' 
DELIMITER ',' CSV HEADER;

